import { requiresDamengIdentifierQuote, requiresMysqlIdentifierQuote, requiresOracleIdentifierQuote, requiresPostgresIdentifierQuote } from "@/lib/sql/sqlIdentifier";
import { tokenIsIdentifier, tokenizeSqlSemantic, unquoteSqlSemanticIdentifier } from "@/lib/sql/semantic/tokens";
import type { SqlSemanticToken } from "@/lib/sql/semantic/types";
import { sqlFormatDialectForDbType, type SqlFormatDialect } from "@/lib/sql/sqlFormatter";
import { dropsSchemaQualifier, quoteTableIdentifier } from "@/lib/table/tableSelectSql";
import type { DatabaseType } from "@/types/database";

const SIMPLE_SQLSERVER_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;

function canRenderUnquoted(identifier: string, dialect: SqlFormatDialect): boolean {
  switch (dialect) {
    case "mysql":
    case "clickhouse":
      return !requiresMysqlIdentifierQuote(identifier);
    case "postgres":
    case "sqlite":
    case "duckdb":
    case "generic":
      return !requiresPostgresIdentifierQuote(identifier);
    case "dameng":
      return !requiresDamengIdentifierQuote(identifier);
    case "oracle":
      return !requiresOracleIdentifierQuote(identifier);
    case "sqlserver":
      return SIMPLE_SQLSERVER_IDENTIFIER.test(identifier) && !requiresMysqlIdentifierQuote(identifier.toLowerCase());
    default:
      return false;
  }
}

/**
 * Resolve the dialect used to read and rewrite DDL text. Callers that only
 * know the connection's syntax-highlighting dialect (which collapses every
 * Oracle-like database onto MySQL) must not have that value decide identifier
 * quoting rules: a case-sensitive Oracle/Dameng name such as `"cName"` would
 * lose its quotes. The effective database type wins, the highlighting dialect
 * stays as the fallback for unmapped types.
 */
export function ddlFormatDialectFor(options: { formatDialect?: SqlFormatDialect; databaseType?: DatabaseType; highlightDialect?: SqlFormatDialect }): SqlFormatDialect {
  if (options.formatDialect) return options.formatDialect;
  const fromDatabaseType = options.databaseType ? sqlFormatDialectForDbType(options.databaseType) : undefined;
  if (fromDatabaseType && fromDatabaseType !== "generic") return fromDatabaseType;
  return options.highlightDialect ?? fromDatabaseType ?? "generic";
}

/** Removes dialect identifier quotes from safe names while preserving strings, comments, and unsafe names. */
export function omitDdlIdentifierQuotes(sql: string, dialect: SqlFormatDialect): string {
  const tokens = tokenizeSqlSemantic(sql, dialect === "sqlserver" ? "sqlserver" : dialect);
  const replacements: Array<{ start: number; end: number; value: string }> = [];

  for (const token of tokens) {
    if (token.kind !== "quoted_identifier") continue;
    const identifier = unquoteSqlSemanticIdentifier(token);
    if (canRenderUnquoted(identifier, dialect)) replacements.push({ start: token.span.start, end: token.span.end, value: identifier });
  }

  let result = sql;
  for (let index = replacements.length - 1; index >= 0; index -= 1) {
    const replacement = replacements[index]!;
    result = `${result.slice(0, replacement.start)}${replacement.value}${result.slice(replacement.end)}`;
  }
  return result;
}

const SIMPLE_ORACLE_IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_$#]*$/;

export interface GeneratedDdlIdentifierQuoteOptions {
  /**
   * Set by structure editors whose edited table already stores a lowercase or
   * mixed-case identifier. Oracle folds bare identifiers to uppercase, so
   * unquoting `"cName"` turns the statement into `CNAME` — a different column,
   * which fails with ORA-00904 or silently creates a differently-cased column.
   * Preserving the case keeps quotes on every name that would change identity
   * while plain names keep the folding behaviour requested in #8997.
   */
  preserveCaseSensitiveIdentifiers?: boolean;
}

/**
 * Applies the identifier-quoting preference to SQL generated by a structure
 * editor. Oracle folds bare identifiers to uppercase, so safe quoted names
 * are uppercased before their quotes are removed. Dameng keeps its stricter
 * case-sensitive identifier rules through omitDdlIdentifierQuotes instead.
 */
export function formatGeneratedDdlIdentifierQuotes(sql: string, dialect: SqlFormatDialect, quoteIdentifiers: boolean, options: GeneratedDdlIdentifierQuoteOptions = {}): string {
  if (quoteIdentifiers) return sql;
  if (dialect !== "oracle") return omitDdlIdentifierQuotes(sql, dialect);

  const preserveCaseSensitive = options.preserveCaseSensitiveIdentifiers === true;
  const tokens = tokenizeSqlSemantic(sql, dialect);
  const replacements: Array<{ start: number; end: number; value: string }> = [];

  for (const token of tokens) {
    if (token.kind !== "quoted_identifier") continue;
    const identifier = unquoteSqlSemanticIdentifier(token);
    if (!SIMPLE_ORACLE_IDENTIFIER.test(identifier) || requiresOracleIdentifierQuote(identifier.toUpperCase())) continue;
    if (preserveCaseSensitive && identifier !== identifier.toUpperCase()) continue;
    replacements.push({ start: token.span.start, end: token.span.end, value: identifier.toUpperCase() });
  }

  let result = sql;
  for (let index = replacements.length - 1; index >= 0; index -= 1) {
    const replacement = replacements[index]!;
    result = `${result.slice(0, replacement.start)}${replacement.value}${result.slice(replacement.end)}`;
  }
  return result;
}

interface DdlSpan {
  start: number;
  end: number;
}

/** Object keywords that can follow `CREATE` once its modifiers are consumed. */
const DDL_CREATE_OBJECT_WORDS = new Set(["table", "view", "index"]);

/**
 * Modifiers that may appear between `CREATE` and the object keyword. Anything
 * outside this set (`function`, `procedure`, `sequence`, ...) is treated as an
 * object kind we do not rewrite, which keeps unrelated DDL untouched.
 */
const DDL_CREATE_MODIFIER_WORDS = new Set(["global", "local", "materialized", "or", "replace", "temporary", "temp", "unlogged", "unique", "clustered", "nonclustered", "columnstore", "fulltext", "spatial", "external"]);

const DDL_ALTER_OBJECT_WORDS = new Set(["table", "view", "index"]);
const DDL_DROP_OBJECT_WORDS = new Set(["table", "view", "index"]);
const DDL_COMMENT_OBJECT_WORDS = new Set(["table", "view", "index", "materialized"]);

/** Skips an optional keyword sequence, returning the original index when it does not match. */
function skipDdlWords(tokens: readonly SqlSemanticToken[], index: number, end: number, words: readonly string[]): number {
  let cursor = index;
  for (const word of words) {
    const token = tokens[cursor];
    if (cursor >= end || !token || token.kind !== "word" || token.normalized !== word) return index;
    cursor += 1;
  }
  return cursor;
}

/** Token indexes of every identifier part of the qualified name starting at `start`. */
function readDdlQualifiedName(tokens: readonly SqlSemanticToken[], start: number, end: number): number[] | undefined {
  if (start >= end || !tokenIsIdentifier(tokens[start])) return undefined;
  const parts = [start];
  let cursor = start + 1;
  while (cursor + 1 < end && tokens[cursor]!.text === "." && tokenIsIdentifier(tokens[cursor + 1])) {
    parts.push(cursor + 1);
    cursor += 2;
  }
  return parts;
}

function findDdlKeyword(tokens: readonly SqlSemanticToken[], start: number, end: number, word: string): number {
  for (let cursor = start; cursor < end; cursor += 1) {
    const token = tokens[cursor]!;
    if (token.depth === 0 && token.kind === "word" && token.normalized === word) return cursor;
  }
  return -1;
}

/**
 * Records the span covering the qualifier chain of a qualified name, keeping
 * only the trailing `keep` parts (`SYSTEM.TEST` with `keep: 1` removes `SYSTEM.`).
 */
function collectDdlQualifierRemoval(tokens: readonly SqlSemanticToken[], parts: readonly number[], keep: number, out: DdlSpan[]): void {
  const firstKept = parts.length - keep;
  if (firstKept <= 0) return;
  out.push({ start: tokens[parts[0]!]!.span.start, end: tokens[parts[firstKept]!]!.span.start });
}

interface DdlNameTarget {
  /** Token indexes of every identifier part of the qualified name. */
  parts: number[];
  /**
   * Trailing parts that must survive a rewrite. `COMMENT ON COLUMN t.c` keeps
   * two (`t.c`), everything else keeps the bare object name.
   */
  keep: number;
  /**
   * Whether a leading database segment may be *inserted*. Index names are
   * scoped to their table (`CREATE INDEX db.idx` is invalid on MySQL and
   * SQL Server), so they stay untouched when the preference is enabled.
   */
  qualifiable: boolean;
}

/** Every qualified name a DDL statement addresses, in source order. */
function collectDdlStatementNameTargets(tokens: readonly SqlSemanticToken[], from: number, to: number, out: DdlNameTarget[]): void {
  let index = from;
  while (index < to && tokens[index]!.kind === "comment") index += 1;
  const head = tokens[index];
  if (!head || head.kind !== "word") return;

  if (head.normalized === "create") {
    let cursor = index + 1;
    while (cursor < to) {
      const token = tokens[cursor]!;
      if (token.kind !== "word") return;
      if (DDL_CREATE_OBJECT_WORDS.has(token.normalized)) break;
      if (!DDL_CREATE_MODIFIER_WORDS.has(token.normalized)) return;
      cursor += 1;
    }
    const objectWord = tokens[cursor];
    if (!objectWord) return;
    cursor = skipDdlWords(tokens, cursor + 1, to, ["if", "not", "exists"]);
    const nameParts = readDdlQualifiedName(tokens, cursor, to);
    if (!nameParts) return;
    out.push({ parts: nameParts, keep: 1, qualifiable: objectWord.normalized !== "index" });
    if (objectWord.normalized === "index") {
      const onIndex = findDdlKeyword(tokens, nameParts[nameParts.length - 1]! + 1, to, "on");
      if (onIndex < 0) return;
      const tableParts = readDdlQualifiedName(tokens, onIndex + 1, to);
      if (tableParts) out.push({ parts: tableParts, keep: 1, qualifiable: true });
    }
    return;
  }

  if (head.normalized === "alter") {
    const objectWord = tokens[index + 1];
    if (!objectWord || objectWord.kind !== "word" || !DDL_ALTER_OBJECT_WORDS.has(objectWord.normalized)) return;
    const nameParts = readDdlQualifiedName(tokens, skipDdlWords(tokens, index + 2, to, ["if", "exists"]), to);
    if (nameParts) out.push({ parts: nameParts, keep: 1, qualifiable: objectWord.normalized !== "index" });
    return;
  }

  if (head.normalized === "drop") {
    const objectWord = tokens[index + 1];
    if (!objectWord || objectWord.kind !== "word" || !DDL_DROP_OBJECT_WORDS.has(objectWord.normalized)) return;
    let cursor = skipDdlWords(tokens, index + 2, to, ["if", "exists"]);
    for (;;) {
      const nameParts = readDdlQualifiedName(tokens, cursor, to);
      if (!nameParts) return;
      out.push({ parts: nameParts, keep: 1, qualifiable: objectWord.normalized !== "index" });
      cursor = nameParts[nameParts.length - 1]! + 1;
      if (tokens[cursor]?.text !== ",") return;
      cursor += 1;
    }
  }

  if (head.normalized === "truncate") {
    let cursor = index + 1;
    if (tokens[cursor]?.kind === "word" && ["table", "only"].includes(tokens[cursor]!.normalized)) cursor += 1;
    const nameParts = readDdlQualifiedName(tokens, cursor, to);
    if (nameParts) out.push({ parts: nameParts, keep: 1, qualifiable: true });
    return;
  }

  if (head.normalized === "comment") {
    if (tokens[index + 1]?.normalized !== "on") return;
    const objectWord = tokens[index + 2];
    if (!objectWord || objectWord.kind !== "word") return;
    const isColumn = objectWord.normalized === "column";
    if (!isColumn && !DDL_COMMENT_OBJECT_WORDS.has(objectWord.normalized)) return;
    const nameParts = readDdlQualifiedName(tokens, index + 3, to);
    // `COMMENT ON COLUMN t.c` keeps `t.c`, so only the schema qualifier goes.
    if (nameParts) out.push({ parts: nameParts, keep: isColumn ? 2 : 1, qualifiable: false });
  }
}

/** Every qualified name addressed by the DDL statements in `sql`, in source order. */
function ddlStatementNameTargets(sql: string, dialect: SqlFormatDialect): { targets: DdlNameTarget[]; tokens: readonly SqlSemanticToken[] } | undefined {
  const tokens = tokenizeSqlSemantic(sql, dialect === "sqlserver" ? "sqlserver" : dialect);
  if (tokens.some((token) => token.closed === false)) return undefined;
  const targets: DdlNameTarget[] = [];
  let statementStart = 0;
  for (let index = 0; index <= tokens.length; index += 1) {
    const token = tokens[index];
    if (token && !(token.kind === "punctuation" && token.text === ";" && token.depth === 0)) continue;
    collectDdlStatementNameTargets(tokens, statementStart, index, targets);
    statementStart = index + 1;
  }
  return { targets, tokens };
}

function collectDdlStatementQualifierRemovals(tokens: readonly SqlSemanticToken[], from: number, to: number, out: DdlSpan[]): void {
  const targets: DdlNameTarget[] = [];
  collectDdlStatementNameTargets(tokens, from, to, targets);
  for (const target of targets) collectDdlQualifierRemoval(tokens, target.parts, target.keep, out);
}

function applyDdlSpans(sql: string, spans: readonly { start: number; end: number; text?: string }[]): string {
  const ordered = [...spans].sort((left, right) => left.start - right.start);
  let result = sql;
  for (let index = ordered.length - 1; index >= 0; index -= 1) {
    const span = ordered[index]!;
    result = `${result.slice(0, span.start)}${span.text ?? ""}${result.slice(span.end)}`;
  }
  return result;
}

/** Engines whose fully qualified table name is `database.table`. */
const DDL_DATABASE_PREFIXED_TYPES = new Set<DatabaseType>(["mysql", "goldendb", "clickhouse"]);
/** Engines whose fully qualified table name is `database.schema.table`. */
const DDL_DATABASE_SCHEMA_PREFIXED_TYPES = new Set<DatabaseType>(["sqlserver"]);

/**
 * Number of parts a fully qualified target name has on this engine, or
 * `undefined` when the engine cannot take a leading database segment (then the
 * DDL stays untouched in both directions).
 */
function ddlQualifiedPartCount(databaseType: DatabaseType | undefined, catalog?: string): number | undefined {
  if (databaseType === undefined) return undefined;
  if (DDL_DATABASE_SCHEMA_PREFIXED_TYPES.has(databaseType)) return 3;
  if (DDL_DATABASE_PREFIXED_TYPES.has(databaseType)) return 2;
  if (databaseType === "doris" || databaseType === "starrocks") {
    // An external catalog already supplies the leading segment
    // (`catalog.database.table`), so the DDL must not grow a second one.
    const external = catalog?.trim();
    return !external || external === "internal" ? 2 : undefined;
  }
  return undefined;
}

/**
 * Applies the "Include database name in generated SQL" preference to the target
 * object of DDL statements (`CREATE/ALTER/DROP TABLE`, `CREATE INDEX ... ON`,
 * `COMMENT ON ...`, `TRUNCATE TABLE`), the same way generated SELECT and
 * copy-as-INSERT SQL honor it.
 *
 * With the preference off the schema/database qualifier is dropped (#9421).
 * With it on, engines whose server never returns the database — MySQL's
 * `SHOW CREATE TABLE` cannot include it — and SQL Server, whose generated DDL
 * stops at `schema.table`, get the leading `database` segment inserted, so a
 * SQL Server table reads `[dbx].[dbo].[t]` (#9262). Databases whose objects
 * cannot be addressed without their qualifier keep it, mirroring
 * `dropsSchemaQualifier`.
 */
export function applyDdlDatabaseQualifier(sql: string, dialect: SqlFormatDialect, databaseType: DatabaseType | undefined, includeDatabaseName: boolean, database?: string, catalog?: string): string {
  if (includeDatabaseName) {
    const qualifiedParts = ddlQualifiedPartCount(databaseType, catalog);
    const databaseName = database?.trim();
    if (qualifiedParts === undefined || !databaseName) return sql;
    const parsed = ddlStatementNameTargets(sql, dialect);
    if (!parsed) return sql;
    const prefix = `${quoteTableIdentifier(databaseType, databaseName)}.`;
    const insertions: Array<DdlSpan & { text: string }> = [];
    for (const target of parsed.targets) {
      // Only a table-like target can be completed: adding a segment to a bare
      // or half-qualified name would invent a namespace the DDL never named,
      // and a `COMMENT ON COLUMN t.c` target is not a database-addressable
      // object.
      if (!target.qualifiable || target.keep !== 1 || target.parts.length !== qualifiedParts - 1) continue;
      const at = parsed.tokens[target.parts[0]!]!.span.start;
      insertions.push({ start: at, end: at, text: prefix });
    }
    if (insertions.length === 0) return sql;
    return applyDdlSpans(sql, insertions);
  }

  if (!dropsSchemaQualifier(databaseType, includeDatabaseName, catalog)) return sql;
  const tokens = tokenizeSqlSemantic(sql, dialect === "sqlserver" ? "sqlserver" : dialect);
  if (tokens.some((token) => token.closed === false)) return sql;

  const removals: DdlSpan[] = [];
  let statementStart = 0;
  for (let index = 0; index <= tokens.length; index += 1) {
    const token = tokens[index];
    if (token && !(token.kind === "punctuation" && token.text === ";" && token.depth === 0)) continue;
    collectDdlStatementQualifierRemovals(tokens, statementStart, index, removals);
    statementStart = index + 1;
  }
  if (removals.length === 0) return sql;

  return applyDdlSpans(sql, removals);
}
