dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.oceanbase:oceanbase-client:2.4.18'
    testImplementation 'com.google.code.gson:gson:2.12.1'
}

tasks.named('shadowJar') {
    manifest {
        attributes('Agent-Label': 'OceanBase Oracle Mode', 'Main-Class': 'com.dbx.agent.oceanbaseoracle.OceanBaseOracleAgent')
    }
}
