dependencies {
    implementation 'com.google.code.gson:gson:2.12.1'
    implementation 'org.slf4j:slf4j-api:1.7.36'
    runtimeOnly 'org.slf4j:slf4j-simple:1.7.36'
}

tasks.named('shadowJar') {
    mergeServiceFiles()
    manifest {
        attributes('Agent-Label': 'LDAP', 'Main-Class': 'com.dbx.agent.ldap.LdapAgent')
    }
}
