dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

tasks.named('shadowJar') {
    manifest {
        attributes(
            'Agent-Label': '\u795e\u901a OSCAR',
            'Agent-External-Driver': 'true',
            'Main-Class': 'com.dbx.agent.oscar.OscarAgent'
        )
    }
}
