// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/xue-ding-e/dbx/plugins/pg-fault-lab/example/model"
)

func newLabOrder(db *gorm.DB, opts ...gen.DOOption) labOrder {
	_labOrder := labOrder{}

	_labOrder.labOrderDo.UseDB(db, opts...)
	_labOrder.labOrderDo.UseModel(&model.LabOrder{})

	tableName := _labOrder.labOrderDo.TableName()
	_labOrder.ALL = field.NewAsterisk(tableName)
	_labOrder.ID = field.NewInt64(tableName, "id")
	_labOrder.Status = field.NewString(tableName, "status")
	_labOrder.Amount = field.NewInt64(tableName, "amount")

	_labOrder.fillFieldMap()

	return _labOrder
}

type labOrder struct {
	labOrderDo labOrderDo

	ALL    field.Asterisk
	ID     field.Int64
	Status field.String
	Amount field.Int64

	fieldMap map[string]field.Expr
}

func (l labOrder) Table(newTableName string) *labOrder {
	l.labOrderDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l labOrder) As(alias string) *labOrder {
	l.labOrderDo.DO = *(l.labOrderDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *labOrder) updateTableName(table string) *labOrder {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.Status = field.NewString(table, "status")
	l.Amount = field.NewInt64(table, "amount")

	l.fillFieldMap()

	return l
}

func (l *labOrder) WithContext(ctx context.Context) ILabOrderDo { return l.labOrderDo.WithContext(ctx) }

func (l labOrder) TableName() string { return l.labOrderDo.TableName() }

func (l labOrder) Alias() string { return l.labOrderDo.Alias() }

func (l labOrder) Columns(cols ...field.Expr) gen.Columns { return l.labOrderDo.Columns(cols...) }

func (l *labOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *labOrder) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 3)
	l.fieldMap["id"] = l.ID
	l.fieldMap["status"] = l.Status
	l.fieldMap["amount"] = l.Amount
}

func (l labOrder) clone(db *gorm.DB) labOrder {
	l.labOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l labOrder) replaceDB(db *gorm.DB) labOrder {
	l.labOrderDo.ReplaceDB(db)
	return l
}

type labOrderDo struct{ gen.DO }

type ILabOrderDo interface {
	gen.SubQuery
	Debug() ILabOrderDo
	WithContext(ctx context.Context) ILabOrderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILabOrderDo
	WriteDB() ILabOrderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILabOrderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILabOrderDo
	Not(conds ...gen.Condition) ILabOrderDo
	Or(conds ...gen.Condition) ILabOrderDo
	Select(conds ...field.Expr) ILabOrderDo
	Where(conds ...gen.Condition) ILabOrderDo
	Order(conds ...field.Expr) ILabOrderDo
	Distinct(cols ...field.Expr) ILabOrderDo
	Omit(cols ...field.Expr) ILabOrderDo
	Join(table schema.Tabler, on ...field.Expr) ILabOrderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILabOrderDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILabOrderDo
	Group(cols ...field.Expr) ILabOrderDo
	Having(conds ...gen.Condition) ILabOrderDo
	Limit(limit int) ILabOrderDo
	Offset(offset int) ILabOrderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILabOrderDo
	Unscoped() ILabOrderDo
	Create(values ...*model.LabOrder) error
	CreateInBatches(values []*model.LabOrder, batchSize int) error
	Save(values ...*model.LabOrder) error
	First() (*model.LabOrder, error)
	Take() (*model.LabOrder, error)
	Last() (*model.LabOrder, error)
	Find() ([]*model.LabOrder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LabOrder, err error)
	FindInBatches(result *[]*model.LabOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.LabOrder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILabOrderDo
	Assign(attrs ...field.AssignExpr) ILabOrderDo
	Joins(fields ...field.RelationField) ILabOrderDo
	Preload(fields ...field.RelationField) ILabOrderDo
	FirstOrInit() (*model.LabOrder, error)
	FirstOrCreate() (*model.LabOrder, error)
	FindByPage(offset int, limit int) (result []*model.LabOrder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILabOrderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l labOrderDo) Debug() ILabOrderDo {
	return l.withDO(l.DO.Debug())
}

func (l labOrderDo) WithContext(ctx context.Context) ILabOrderDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l labOrderDo) ReadDB() ILabOrderDo {
	return l.Clauses(dbresolver.Read)
}

func (l labOrderDo) WriteDB() ILabOrderDo {
	return l.Clauses(dbresolver.Write)
}

func (l labOrderDo) Session(config *gorm.Session) ILabOrderDo {
	return l.withDO(l.DO.Session(config))
}

func (l labOrderDo) Clauses(conds ...clause.Expression) ILabOrderDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l labOrderDo) Returning(value interface{}, columns ...string) ILabOrderDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l labOrderDo) Not(conds ...gen.Condition) ILabOrderDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l labOrderDo) Or(conds ...gen.Condition) ILabOrderDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l labOrderDo) Select(conds ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l labOrderDo) Where(conds ...gen.Condition) ILabOrderDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l labOrderDo) Order(conds ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l labOrderDo) Distinct(cols ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l labOrderDo) Omit(cols ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l labOrderDo) Join(table schema.Tabler, on ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l labOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l labOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l labOrderDo) Group(cols ...field.Expr) ILabOrderDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l labOrderDo) Having(conds ...gen.Condition) ILabOrderDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l labOrderDo) Limit(limit int) ILabOrderDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l labOrderDo) Offset(offset int) ILabOrderDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l labOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILabOrderDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l labOrderDo) Unscoped() ILabOrderDo {
	return l.withDO(l.DO.Unscoped())
}

func (l labOrderDo) Create(values ...*model.LabOrder) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l labOrderDo) CreateInBatches(values []*model.LabOrder, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l labOrderDo) Save(values ...*model.LabOrder) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l labOrderDo) First() (*model.LabOrder, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LabOrder), nil
	}
}

func (l labOrderDo) Take() (*model.LabOrder, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LabOrder), nil
	}
}

func (l labOrderDo) Last() (*model.LabOrder, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LabOrder), nil
	}
}

func (l labOrderDo) Find() ([]*model.LabOrder, error) {
	result, err := l.DO.Find()
	return result.([]*model.LabOrder), err
}

func (l labOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LabOrder, err error) {
	buf := make([]*model.LabOrder, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l labOrderDo) FindInBatches(result *[]*model.LabOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l labOrderDo) Attrs(attrs ...field.AssignExpr) ILabOrderDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l labOrderDo) Assign(attrs ...field.AssignExpr) ILabOrderDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l labOrderDo) Joins(fields ...field.RelationField) ILabOrderDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l labOrderDo) Preload(fields ...field.RelationField) ILabOrderDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l labOrderDo) FirstOrInit() (*model.LabOrder, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LabOrder), nil
	}
}

func (l labOrderDo) FirstOrCreate() (*model.LabOrder, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LabOrder), nil
	}
}

func (l labOrderDo) FindByPage(offset int, limit int) (result []*model.LabOrder, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l labOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l labOrderDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l labOrderDo) Delete(models ...*model.LabOrder) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *labOrderDo) withDO(do gen.Dao) *labOrderDo {
	l.DO = *do.(*gen.DO)
	return l
}
